"""'table indexes'

Revision ID: 313a5c223435
Revises: 9bab4ec1d255
Create Date: 2025-06-02 19:27:19.816955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313a5c223435'
down_revision: Union[str, None] = '9bab4ec1d255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        'idx_drug_catalogs_country_id', 'drug_catalogs',
        ['country', 'id'], unique=False)
    op.create_index(
        'idx_drug_catalogs_name_trgm', 'drug_catalogs',
        ['name'], unique=False, postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(
        'idx_drugs_catalog_id_id', 'drugs',
        ['catalog_id', 'id'], unique=False)
    op.create_index(
        'idx_drugs_drug_name_trgm', 'drugs',
        ['drug_name'], unique=False, postgresql_using='gin',
        postgresql_ops={'drug_name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'idx_drugs_drug_name_trgm', table_name='drugs',
        postgresql_using='gin', postgresql_ops={'drug_name': 'gin_trgm_ops'})
    op.drop_index(
        'idx_drugs_catalog_id_id', table_name='drugs')
    op.drop_index(
        'idx_drug_catalogs_name_trgm', table_name='drug_catalogs',
        postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(
        'idx_drug_catalogs_country_id', table_name='drug_catalogs')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
