"""'central drug catalog'

Revision ID: 352f8e72b22c
Revises: 993dcd4b8b65
Create Date: 2025-04-16 12:59:14.913513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352f8e72b22c'
down_revision: Union[str, None] = '993dcd4b8b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_catalogs', sa.Column(
        'is_central', sa.Boolean(), nullable=True))
    op.execute("UPDATE drug_catalogs SET is_central = false")
    op.alter_column('drug_catalogs', 'is_central', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_catalogs', 'is_central')
    # ### end Alembic commands ###
