"""init

Revision ID: 3b772a23c3d5
Revises: 
Create Date: 2024-08-30 12:37:12.712591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b772a23c3d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'PROCESSING', 'DONE', name='entitystatus').create(op.get_bind())
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'DONE', name='entitystatus', create_type=False), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('_entity_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    sa.Enum('type1', 'type2', name='entity_status').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('type1', 'type2', name='entity_status').create(op.get_bind())
    op.drop_table('transaction')
    op.drop_table('entity')
    sa.Enum('PENDING', 'PROCESSING', 'DONE', name='entitystatus').drop(op.get_bind())
    # ### end Alembic commands ###
