"""'autogenerated'

Revision ID: 5d04ad429a57
Revises: 449357e0c022
Create Date: 2025-08-12 15:41:43.727584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d04ad429a57'
down_revision: Union[str, None] = '449357e0c022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_catalog_transactions_transaction_id",
        'catalog_transactions', ['transaction_id'])
    op.create_index(
        'idx_drugs_catalog_id', 'drugs', ['catalog_id'], unique=False)
    op.create_index(
        'idx_drugs_drug_code_trgm', 'drugs', ['drug_code'], unique=False,
        postgresql_using='gin', postgresql_ops={'drug_code': 'gin_trgm_ops'})
    op.create_unique_constraint(
        "uq_mapping_transactions_transaction_id",
        'mapping_transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_mapping_transactions_transaction_id",
        'mapping_transactions', type_='unique')
    op.drop_index(
        'idx_drugs_drug_code_trgm', table_name='drugs',
        postgresql_using='gin', postgresql_ops={'drug_code': 'gin_trgm_ops'})
    op.drop_index(
        'idx_drugs_catalog_id', table_name='drugs')
    op.drop_constraint(
        "uq_catalog_transactions_transaction_id",
        'catalog_transactions', type_='unique')
    # ### end Alembic commands ###
