"""'drug and drug mapping'

Revision ID: 993dcd4b8b65
Revises: 6d46a949e3f2
Create Date: 2025-04-09 15:27:35.291737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993dcd4b8b65'
down_revision: Union[str, None] = '6d46a949e3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'drugs',
        sa.Column('catalog_id', sa.BigInteger(), nullable=False),
        sa.Column('drug_code', sa.String(), nullable=False),
        sa.Column('drug_name', sa.String(), nullable=False),
        sa.Column('properties', sa.JSON(), nullable=True),
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['catalog_id'], ['drug_catalogs.id'],
                                name='fk_drug_catalog'),
        sa.PrimaryKeyConstraint('id', name='drugs_pkey'),
    )
    op.create_table(
        'drug_mappings',
        sa.Column('drug_id', sa.BigInteger(), nullable=False),
        sa.Column('related_drug_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'],
                                name='fk_drug_mapping_drug'),
        sa.ForeignKeyConstraint(['related_drug_id'], ['drugs.id'],
                                name='fk_drug_mapping_related_drug'),
        sa.PrimaryKeyConstraint('drug_id', 'related_drug_id',
                                name='uq_drug_related_drug')
    )
    op.alter_column('ledger_transactions', 'content',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Text(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ledger_transactions', 'content',
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False)
    op.drop_table('drug_mappings')
    op.drop_table('drugs')
    # ### end Alembic commands ###
