"""'Import Drug Catalog and Mappings transactions tables'

Revision ID: 9bab4ec1d255
Revises: 947b8ca40067
Create Date: 2025-05-16 09:36:04.747807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bab4ec1d255'
down_revision: Union[str, None] = '947b8ca40067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'catalog_transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('catalog_id', sa.BigInteger(), nullable=False),
        sa.Column('transaction_id', sa.UUID(), nullable=False),

        sa.ForeignKeyConstraint(
            ['catalog_id'], ['drug_catalogs.id'],
            name='catalog_transactions_catalog_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='catalog_transactions_pkey'),
        sa.UniqueConstraint(
            'transaction_id', name='catalog_transactions_transaction_id_uniq')
    )
    op.create_table(
        'mapping_transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('mapping_id', sa.BigInteger(), nullable=False),
        sa.Column('catalog_id', sa.BigInteger(), nullable=False),
        sa.Column('related_catalog_id', sa.BigInteger(), nullable=False),
        sa.Column('transaction_id', sa.UUID(), nullable=False),

        sa.ForeignKeyConstraint(
            ['catalog_id'], ['drug_catalogs.id'],
            name='mapping_transactions_catalog_id_fkey'),
        sa.ForeignKeyConstraint(
            ['related_catalog_id'], ['drug_catalogs.id'],
            name='mapping_transactions_related_catalog_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='mapping_transactions_pkey'),
        sa.UniqueConstraint('transaction_id',
                            name='mapping_transactions_transaction_id_uniq')
    )
    op.drop_table('ledger_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ledger_transactions',
        sa.Column('transaction_id', sa.VARCHAR(length=50),
                  autoincrement=False, nullable=False),
        sa.Column('entity_name', sa.VARCHAR(),
                  autoincrement=False, nullable=False),
        sa.Column('entity_id', sa.BIGINT(),
                  autoincrement=False, nullable=False),
        sa.Column('content', sa.TEXT(),
                  autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True),
                  server_default=sa.text('now()'),
                  autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            'transaction_id', name='ledger_transactions_pkey')
    )
    op.drop_table('mapping_transactions')
    op.drop_table('catalog_transactions')
    # ### end Alembic commands ###
