"""'autogenerated'

Revision ID: c05ba0df6ca3
Revises: 
Create Date: 2025-04-03 01:21:54.328798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.domain.entities.user import User


# revision identifiers, used by Alembic.
revision: str = 'c05ba0df6ca3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'drug_catalogs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('file_transaction_id', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_drug_catalogs'),
    )
    op.create_table(
        'ledger_transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('transaction_id', sa.String(length=100), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_ledger_transactions'),
    )
    op.create_table(
        'users',
        sa.Column('sub', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('sub', name='pk_users'),
        sa.UniqueConstraint('email', name='ux_users_email')
    )

    # Add a default record to the 'users' table
    users_table = sa.table(
        'users',
        sa.column('sub', sa.BigInteger),
        sa.column('name', sa.String),
        sa.column('email', sa.String),
        sa.column('password', sa.String)
    )
    default_user = User("John Doe", "johndoe@example.com", "mysecretpassword")
    op.bulk_insert(users_table, [default_user._alembic_user()])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ledger_transactions')
    op.drop_table('drug_catalogs')
    # ### end Alembic commands ###
