from enum import Enum


class ErrorCodes(str, Enum):
    NOT_FOUND = 'NOT_FOUND'
    ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND'
    DATA_EXISTS = 'DATA_EXISTS'
    NAME_ALREADY_IN_USE = 'NAME_ALREADY_IN_USE'
    RESOURCE_STILL_PROCESSING = 'RESOURCE_STILL_PROCESSING'
    LEDGER_ERROR = 'LEDGER_ERROR'
